# Generated by Django 6.1 on 2026-08-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('notes', 'Notes'), ('pdf', 'PDF'), ('revision', 'Quick Revision'), ('example', 'Example')], default='notes', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Study material content')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.topic')),
            ],
        ),
    ]
